Feat(role)-add-homeassistant
saltyorg/Sandbox pull request #174
Opened 2022-11-13 03:18 UTC by RaneyDazed

# Description

This PR is for Home assistant, it is open source home automation that puts local control and privacy first. Its powered by a worldwide community of tinkerers and DIY enthusiasts. Perfect to run on a Raspberry Pi or a local server. Docker compose: 

```yaml
version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - /opt/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
```

It connects to LAN devices just fine, and is connectable after initial setup on lan IP, ie `192.168.1.xx:8123`

# Doccumentations 

I will create the docs post haste!

# How Has This Been Tested?

I tested it many times on my local server, removing files and the directory multiple times. Salty gave me a hand with it a few times, figuring out what would allow host mode. Requires newest update of sb and traefik. To allow for the role to work with docker network mode: host.

2022-11-13 03:23 UTC, owine commented
Tag not added to sandbox.yml

2022-11-13 03:25 UTC, RaneyDazed commented
Yup I'd realized that a second ago, fixing rn

2022-11-13 03:33 UTC, RaneyDazed commented
Sorry I'd reverted back to master and didn't realize it. Should be set now.

2022-11-13 09:57 UTC, keldian commented
The right name is _home-assistant_, not _homeassistant_.

2022-11-13 23:48 UTC, JigSawFr requested changes

2022-11-13 23:48 UTC, JigSawFr commented on roles/homeassistant/defaults/main.yml
> +
Please add healthcheck block here :)

2022-11-14 15:46 UTC, owine commented
If someone runs this role on a remote server in a datacenter, rather on a local LAN, do we introduce any issues?

2022-11-14 15:59 UTC, owine requested changes
If someone runs this role on a remote server in a datacenter, rather on a local LAN, do we introduce any issues?

2022-11-14 17:31 UTC, RaneyDazed commented
> If someone runs this role on a remote server in a datacenter, rather on a local LAN, do we introduce any issues?

I will run it on my hetzner and see. I don't forsee any issues, but it wont do you any good really. What issues did you have in mind?

2022-11-14 18:52 UTC, JigSawFr commented
@owine suggested to have a global var like home-use: true/false in settings of saltbox and block some roles depending of the value to avoid an issue, same for homebridge, pi-hole, etc
Another way is to not publish ports, and assume that user will use a vpn (like wireguard) container to consume them. (Or manually override to publish port).

2022-11-14 18:54 UTC, RaneyDazed commented
Looks like I need to figure out this rebase thing before this will go anywhere

2022-11-17 01:03 UTC, RaneyDazed commented
So where are we with homeassistant @JigSawFr @owine 

Is there something I'm supposed to do to somehow set it local only? I haven't installed on my remote server yet. I can do that then what am I looking for? anything in particular?

2022-11-17 01:03 UTC, RaneyDazed commented
We can always put it on hold if necessary if we are waiting for some kind of true false local thing?

2022-11-17 01:10 UTC, owine commented
I don’t care about a toggle, just want to make sure this won’t cause issues on a remote servers.

2022-11-20 11:11 UTC, RaneyDazed commented
Tested on my remote server and didn't have any trouble. Loaded up just fine, logged in made a user etc.

2022-11-20 15:44 UTC, merged