add youtubedl_material role
saltyorg/Sandbox pull request #313
Opened 2023-12-22 00:56 UTC by hereisderek

# Description

YoutubeDL-Material is a Material Design frontend for [youtube-dl](https://rg3.github.io/youtube-dl/). It's coded using [Angular 15](https://angular.io/) for the frontend, and [Node.js](https://nodejs.org/) on the backend.

Project page: [link](https://github.com/Tzahi12345/YoutubeDL-Material)

TODO:
- [ ] doc page

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Please also note any relevant details for your test configuration.  You can use the checkboxes below or delete them as you wish.

- [x] tested with `sb install youtubedl_material`
- [x] access the subdomain `https://ytdl.domain.com` and tested it's working

2023-12-22 01:48 UTC, saltydk requested changes
Please review the requested changes.

2023-12-22 01:48 UTC, saltydk commented on roles/youtubedl_material/defaults/main.yml
> +# Author(s):        Tzahi12345                                           #
Wrong author, this is you not the upstream project creator

2023-12-22 01:48 UTC, saltydk commented on roles/youtubedl_material/defaults/main.yml
> +# URL:              https://github.com/Tzahi12345/YoutubeDL-Material     #
Supposed to be Sandbox url

2023-12-22 01:48 UTC, saltydk commented on roles/youtubedl_material/defaults/main.yml
> +youtubedl_material_download_folder: "/mnt/unionfs/Media/{{ youtubedl_material_name }}"
Downloads generally do not go into Media folders

2023-12-22 01:48 UTC, saltydk commented on roles/youtubedl_material/defaults/main.yml
> +youtubedl_material_web_url: "{{ 'https://' + youtubedl_material_web_subdomain + '.' + youtubedl_material_web_domain
Look at other roles for a reference on how to format this

2023-12-22 01:48 UTC, saltydk commented on roles/youtubedl_material/defaults/main.yml
> +youtubedl_material_traefik_middleware: "{{ traefik_default_middleware + ',' + youtubedl_material_traefik_sso_middleware
Look at other roles for a reference on how to format this

2023-12-22 01:48 UTC, saltydk commented on roles/youtubedl_material/defaults/main.yml
> +youtubedl_material_docker_ports: "{{ youtubedl_material_docker_ports_defaults
Look at other roles for a reference on how to format this

2023-12-22 01:48 UTC, saltydk commented on roles/youtubedl_material/defaults/main.yml
> +youtubedl_material_docker_envs: "{{ youtubedl_material_docker_envs_default
Look at other roles for a reference on how to format this

2023-12-22 01:48 UTC, saltydk commented on roles/youtubedl_material/defaults/main.yml
> +  # ytdl_use_local_db: 'false'
This is useless, either implement a variable to toggle this behavior or remove it

2023-12-22 01:48 UTC, saltydk commented on roles/youtubedl_material/defaults/main.yml
> +  PUID: "{{ uid }}"
Based on a quick glance the container does not support PUID/PGID check [here](https://github.com/Tzahi12345/YoutubeDL-Material#custom-uidgid)

2023-12-22 01:48 UTC, saltydk commented on roles/youtubedl_material/defaults/main.yml
> +youtubedl_material_docker_commands: "{{ youtubedl_material_docker_commands_default
Look at other roles for a reference on how to format this

2023-12-22 01:48 UTC, saltydk commented on roles/youtubedl_material/defaults/main.yml
> +youtubedl_material_docker_volumes: "{{ youtubedl_material_docker_volumes_default
Look at other roles for a reference on how to format this and remove docker_volumes_downloads_common as it is already included

2023-12-22 01:48 UTC, saltydk commented on roles/youtubedl_material/defaults/main.yml
> +youtubedl_material_docker_devices: "{{ youtubedl_material_docker_devices_default
Look at other roles for a reference on how to format this

2023-12-22 01:48 UTC, saltydk commented on roles/youtubedl_material/defaults/main.yml
> +youtubedl_material_docker_hosts: "{{ docker_hosts_common
Look at other roles for a reference on how to format this

2023-12-22 01:48 UTC, saltydk commented on roles/youtubedl_material/defaults/main.yml
> +youtubedl_material_docker_labels: "{{ docker_labels_common
Look at other roles for a reference on how to format this

2023-12-22 01:48 UTC, saltydk commented on roles/youtubedl_material/defaults/main.yml
> +youtubedl_material_docker_networks: "{{ docker_networks_common
Look at other roles for a reference on how to format this

2023-12-22 01:48 UTC, saltydk commented on roles/youtubedl_material/defaults/main.yml
> +youtubedl_material_docker_capabilities: "{{ youtubedl_material_docker_capabilities_default
Look at other roles for a reference on how to format this

2023-12-22 01:48 UTC, saltydk commented on roles/youtubedl_material/defaults/main.yml
> +youtubedl_material_docker_security_opts: "{{ youtubedl_material_docker_security_opts_default
Look at other roles for a reference on how to format this

2023-12-22 01:48 UTC, saltydk commented on sandbox.yml
> +    - { role: youtubedl_material, tags: ['youtubedl_material'] }
We no longer accept underscores in tags

2024-01-08 02:25 UTC, saltydk commented
Close this if you don't want to do the changes for him @owine since he hasn't responded for 2 weeks I assume this will remain stagnant.

2024-01-13 21:00 UTC, closed without merging

2024-01-13 21:00 UTC, owine commented
Happy to reopen and revisit if the requested changes are made